// <auto-generated />
using HangApi.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HangApi.Migrations
{
    [DbContext(typeof(WordsContext))]
    [Migration("20230204175400_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("HangApi.Models.Words", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WordFive")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WordFour")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WordOne")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WordThree")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WordTwo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("wordss");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Theme = "animals",
                            WordFive = "zebra",
                            WordFour = "hipopotomus",
                            WordOne = "panther",
                            WordThree = "frog",
                            WordTwo = "giraffe"
                        },
                        new
                        {
                            Id = 2,
                            Theme = "lithuanian cities",
                            WordFive = "klaipeda",
                            WordFour = "panevezys",
                            WordOne = "kaunas",
                            WordThree = "siauliai",
                            WordTwo = "vilnius"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
